### ISSUE TITLE
"View on explorer" gives a ERR_FILE_NOT_FOUND.

### ISSUE THREAD

**Issue by t00k** [allemanfredi/PEGASUS#12]
Windows 10
Google Chrome Version 81.0.4044.122.

Clicking "View on explorer" on the ...-menu to the right of your wallet name takes you nowhere.
Gives you a "ERR_FILE_NOT_FOUND" on the destination.

**Comment by allemanfredi** [comment]
Helo @t00k !

Thanks for having reported it to me! just fixed!
