### ISSUE TITLE
Not a real issue

### ISSUE THREAD

**Issue by huhn511** [allemanfredi/PEGASUS#4]
Nice work - if you're going to ship this into a test phase, please let me know. I would like to write an article about this project for www.einfachiota.de

If you have discord, you could add me there (huhn#0511)

Thanks 👏

**Comment by allemanfredi** [comment]
Hello @huhn511!! 
Thank you very much! Currently the extension is going to be published on chrome web store. I'm just waiting the review.

About the article, i would be very pleased!
