### ISSUE TITLE
T.initStorageDataService is not a function

### ISSUE THREAD

**Issue by jaredxx1** [allemanfredi/PEGASUS#9]
Hello!

When trying to restore from seed I get the message in the title.

It would be nice to be able to import the seed.

**Comment by allemanfredi** [comment]
Hello @jaredxx1 sorry for the problem! i will fix it as soon as possible!

**Comment by allemanfredi** [comment]
Hello sorry for the issue and thank you for having report it! this [commit](https://github.com/allemanfredi/PEGASUS/commit/c2bb56c9c3a7bfbba8ae08552953923d9b93c84)  fixed it!
